application: datasource-airmap
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:

#image
- url: /image/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: assets/image/\1
  upload: assets/image/(.*\.(bmp|gif|ico|jpeg|jpg|png))

#css
- url: /css/(.*\.css)
  static_files: assets/css/\1
  upload: assets/css/(.*\.css)
  mime_type: text/css

#js
- url: /js/(.*\.js)
  static_files: assets/js/\1
  upload: assets/js/(.*\.js)
  mime_type: application/javascript

- url: /log
  script: /public/log.php
  secure: always

- url: /cron
  script: /cron.php

- url: /(.+)\.json
  script: /public/json.php
  secure: always

- url: /admin
  script: /public/admin.php
  secure: always

- url: /user
  script: /public/user.php
  secure: always

- url: /config
  script: /public/config.php
  secure: always

- url: /query-history
  script: /public/query-history.php
  secure: always

- url: /query-lastest
  script: /public/query-lastest.php
  secure: always

- url: /(.*)
  script: /public/index.php
  secure: always

skip_files:
- ^(.*/)?.*/node_modules/.*$
- ^(node_modules/.*)
- ^(.git/.*)